import pygame
# game window dimensions
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600

# game variables
FPS = 60
PLAYER_X = SCREEN_WIDTH // 2
PLAYER_Y = SCREEN_HEIGHT - 150
PLATFORM_IMG_SCALER = 30
STARTING_PLATFORM_WIDTH = 100
STARTING_PLATFORM_X = SCREEN_WIDTH // 2 - 50
STARTING_PLATFORM_Y = SCREEN_HEIGHT - 50
JUMP_SPEED = 20
SIDE_MOVE_SPEED = 10
SCROLL_THRESH = 200
GRAVITY = 1
MAX_PLATFORMS = 10
PLAYER_WIDTH = 25
PLAYER_HEIGHT = 50
PLAYER_IMAGE_SCALE = 45
PLAYER_RECTANGLE_X_OFFSET = 12
PLAYER_RECTANGLE_Y_OFFSET = 5
PLATFROM_WIDTH_FROM = 60
PLATFROM_WIDTH_TILL = 80
ENEMY_IMAGE_SCALE = 70
ENEMY_SPEED  = 3
ENEMY_SPAWN_Y = 0
CHANCE_FOR_2_PLATFORMS = 0.5
# define colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
